# Generated by Django 2.2.12 on 2020-05-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
